### ISSUE TITLE
I don't know where else to put this...

### ISSUE THREAD

**Issue by iam-py-test** [iam-py-test/Badware-Reports-1#7]
@flawlessdeveloper, the website linked from your profile is blocked as malware
I don't know why it is blocked (it just cryptically said there was a trojan), but I thought you might want to know so you can fix the issue.
I posted this in one of my repos because I could not open one in any of your repos.

**Comment by FlawlessDeveloper** [comment]
Hey thanks for letting me know. Ill try to resolve this. You can keep in touch with me on discord FlawlessCode#0001

**Comment by iam-py-test** [comment]
I don’t have a Discord account, so can we use GitHub?

**Comment by FlawlessDeveloper** [comment]
Yea. Sorry for the long silence. Could you provide me with a screenshot or more information regarding the site?

**Comment by iam-py-test** [comment]
I use Malwarebytes Browser Guard (it is free and seems ok at malware blocking).
Here is its report:
![image](https://user-images.githubusercontent.com/84232764/125205849-48b5c600-e252-11eb-8a4f-df164a5fcf95.png)
Sadly Malwarebytes lacks an online lookup tool or else I would get more data

**Comment by iam-py-test** [comment]
I am looking in a VM for signs of malware
Please wait..

**Comment by iam-py-test** [comment]
Nothing obviously malicious, however, the about link does not work

**Comment by FlawlessDeveloper** [comment]
Ill take a look at the whole file structure. This is especially weird, because if there is smth malicious on the site i definitivly did not plant it. At that point I probably have to assume my server has been infected.

**Comment by iam-py-test** [comment]
> Ill take a look at the whole file structure. This is especially weird, because if there is smth malicious on the site i definitivly did not plant it. At that point I probably have to assume my server has been infected.

As stated above, it is probably a FP.

**Comment by FlawlessDeveloper** [comment]
I had a look at the files and there was nothing hidden or mailcious so your probably right with your assumption 👍🏽 Thx for reporting it to me 😄

**Comment by iam-py-test** [comment]
Should I chose this issue or should we wait until the FP has been fixed?

**Comment by iam-py-test** [comment]
Whoops! Clicked the wrong button

**Comment by FlawlessDeveloper** [comment]
Idk how mb handles fp's so i guess it should stay opened until confirmed

**Comment by iam-py-test** [comment]
@FlawlessDeveloper sign up to Malwarebytes Forums - here https://forums.malwarebytes.com/register/ 
And then post to https://forums.malwarebytes.com/forum/123-website-blocking/

**Comment by FlawlessDeveloper** [comment]
Could you provide me with with the mbam logs?
![image](https://user-images.githubusercontent.com/37778817/125323679-5ac16280-e33f-11eb-89fd-656d408bc723.png)

**Comment by iam-py-test** [comment]
> Could you provide me with with the mbam logs?
> ![image](https://user-images.githubusercontent.com/37778817/125323679-5ac16280-e33f-11eb-89fd-656d408bc723.png)

Let me try...
Please wait

**Comment by iam-py-test** [comment]
@FlawlessDeveloper This is from using the ping command, but should have similar data
[mb_log.txt](https://github.com/iam-py-test/Badware-Reports-1/files/6803000/mb_log.txt)

**Comment by FlawlessDeveloper** [comment]
I opened a topic on the forum. I hope itll get resolved asap.

**Comment by iam-py-test** [comment]
Would you mind posting the link so I can follow it?

**Comment by FlawlessDeveloper** [comment]
![image](https://user-images.githubusercontent.com/37778817/125327583-8fcfb400-e343-11eb-8832-fd68c2f5b19c.png)
This got resolved very quickly.

**Comment by iam-py-test** [comment]
@FlawlessDeveloper thank you!

**Comment by FlawlessDeveloper** [comment]
Thank you as well

**Comment by iam-py-test** [comment]
I just noticed and wanted to help!
Just glad this was resolved
